# Generated by Django 5.0.7 on 2024-07-23 00:44

import django.db.models.deletion
import imagens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensHistorico',
            fields=[
                ('id_imagem_historico', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=imagens.models.imagens_historico)),
                ('id_historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='historicos.historicos')),
            ],
        ),
    ]
