# Generated by Django 5.0.7 on 2024-07-24 23:46

import django.db.models.deletion
import imagens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagens', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensPaciente',
            fields=[
                ('id_imagem_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=imagens.models.imagens_paciente)),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='pacientes.pacientes')),
            ],
        ),
    ]
